"""migration

Revision ID: 9f44a13169ed
Revises: 817537746852
Create Date: 2024-05-30 20:41:20.944920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f44a13169ed'
down_revision: Union[str, None] = '817537746852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
